### ISSUE TITLE
Swipe step is not working with integration_test

### ISSUE THREAD

**Issue by Nolat** [jonsamwell/flutter_gherkin#159]
The step "I swipe [down|left|right|up] by {int} pixels on the {string}" is not working on the 3.0.0-rc.5.

![image](https://user-images.githubusercontent.com/22156783/136797362-ad036a9b-d02c-4afb-a3af-eebec7c82b44.png)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.2.3 20D91 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.61.0-insider)
[✓] Connected device (1 available)

**Comment by jonsamwell** [comment]
Thanks for reporting this. I'll get a fix in

**Comment by TomBenaiteau** [comment]
Hello, i tried the "swipe" step on the 3.0.0-rc.6, and it still doesn't work.
I suspect the scroll function to not working on the file app_driver_adapter.

![Capture d’écran 2021-11-08 à 09 26 53](https://user-images.githubusercontent.com/70884460/140709354-5b49b0fb-7b46-44d7-86b0-dac7ecdf576e.png)


[✓] Flutter (Channel stable, 2.5.1, on macOS 11.4 20F71 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.0)
[✓] Connected device (1 available)

**Comment by jonsamwell** [comment]
@TomBenaiteau are you able to set up a reproduction of this so I can debug it?

**Comment by jonsamwell** [comment]
@TomBenaiteau should be fixed in 3.0.0-rc.7

**Comment by TomBenaiteau** [comment]
I tried on 3.0.0-rc.7, and I still get the same error, so I tried with your example, and it works fine, but the problem is with the widget we are using. We are using a "ListWheelScrollView". You can debug it with this widget and find the same error with the example I give you. Can you watch it, thank you.

```dart
import 'package:flutter/material.dart';

class ListWheelScrollViewApp extends StatefulWidget {
  @override
  _ListWheelScrollViewAppState createState() {
    return _ListWheelScrollViewAppState();
  }
}

class _ListWheelScrollViewAppState extends State<ListWheelScrollViewApp> {
  int _selectedItemIndex = 0;

  @override
  Widget build(BuildContext context) {
    List<Widget> items = [
      ListTile(
        leading: Icon(Icons.local_activity, size: 50),
        title: Text('Activity'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_airport, size: 50),
        title: Text('Airport'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_atm, size: 50),
        title: Text('ATM'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_bar, size: 50),
        title: Text('Bar'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_cafe, size: 50),
        title: Text('Cafe'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_car_wash, size: 50),
        title: Text('Car Wash'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_convenience_store, size: 50),
        title: Text('Convenience Store'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_dining, size: 50),
        title: Text('Dining'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_drink, size: 50),
        title: Text('Drink'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_florist, size: 50),
        title: Text('Florist'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_gas_station, size: 50),
        title: Text('Gas Station'),
        subtitle: Text('Description here'),
      ),
      ListTile(
        leading: Icon(Icons.local_grocery_store, size: 50),
        title: Text('Grocery Store'),
        subtitle: Text('Description here'),
      ),
    ];

    return Scaffold(
        appBar: AppBar(
          title: Text('Woolha.com Flutter Tutorial'),
        ),
        body: Center(
            child: ListWheelScrollView(
          key: const Key('scrollable cards'),
          itemExtent: 75,
          children: items,
          magnification: 1.5,
          useMagnifier: true,
          physics: FixedExtentScrollPhysics(),
          diameterRatio: 1.5,
          squeeze: 0.8,
          onSelectedItemChanged: (index) => {
            setState(() {
              _selectedItemIndex = index;
            })
          },
        )));
  }
}
```
