### ISSUE TITLE
Incorrect feature name in HTML reports

### ISSUE THREAD

**Issue by umangdivyanshu** [jonsamwell/flutter_gherkin#162]
In the HTML report, correct feature name is not publishing. For each feature, the first scenario name is getting published for feature name in the report.

I am using 3.0.0-rc.3 with integration_test support.

**Comment by jonsamwell** [comment]
Closing as fixed in rc-6

**Comment by umangdivyanshu** [comment]
I have upgraded to 3.0.0-rc.6 and the issue still persists. In the HTML report, the first scenario name is getting published for feature name in the report. Plase see attached screenshot for reference.
![Screenshot 2021-11-02 at 12 06 59 PM](https://user-images.githubusercontent.com/77405518/139798021-f375d6ea-c2c5-4691-ab80-bfa6ad74783e.png)

**Comment by jonsamwell** [comment]
Ah OK I will take a look - thank for reporting.

**Comment by umangdivyanshu** [comment]
**Adding one more issue w.r.t. reporting in this.**

After using tags in the configuration, the HTML report has only one scenario listed. Scenarios from other feature files are rendering under only one feature in the report.

Validate login with valid credentials is a part of a separate feature file and Adding new watches to the product list is a part of a different feature file. But both are rendering under same feature in the report.

![image](https://user-images.githubusercontent.com/77405518/140025751-4bcdf02e-ec17-40de-b344-c6cefa291dd4.png)

**Comment by AFASbart** [comment]
So I am having this problem aswell, I have looked in the code. Apparently the function onFeatureStarted gets the name and id of the first scenario instead of the feature name. After some debugging I found that it is an problem with the feature to .g.dart file. In the .g.dart file the title is inproperly stated.

**Comment by jonsamwell** [comment]
@AFASbart thanks for looking into this so do you think the problem is the name that the onFeatureStarted function gets?

**Comment by AFASbart** [comment]
So I have figured it out. It is in the gherkin_suite_test_generator. You call the visitScenario() function. But the feature name does not get given with it. Then the onBefore etc should contain the feature name. I have fixed it locally (will make PR tomorrow @ work). You can review it then. The ON_BEFORE_SCENARIO_RUN variable should change scenario_name to feature_name. And then add a block 
`_currentScenarioCode = _replaceVariable(
      _currentScenarioCode!,
      'feature_name',
      _escapeText(featureName),
    );`

These will be the changed variables: 
`static const String ON_BEFORE_SCENARIO_RUN = '''
  () async => onBeforeRunFeature('{{feature_name}}', {{tags}},)
  ''';
  static const String ON_AFTER_SCENARIO_RUN = '''
  () async => onAfterRunFeature('{{feature_name}}',)
  ''';`

For me it is now 10:30PM so I will update it tomorrow. (If you want to fix it now you can search for the variable names and the function visitScenario(). It should be called with an extra parameter (I called it featureName). Then in the builder you have to edit the abstract class and the function call (ofcourse).

**Comment by jonsamwell** [comment]
@AFASbart many thanks for this.  Looking at it now.  I think we'll need to pass the feature tags as well as they are the scenarios tags at the moment.  

I'll try and looks at this today.

**Comment by BartVerm779** [comment]
(I'm @AFASbart but this is my personal account), we'll have to add because the scenarioname etc is also used in the function. So we can't replace it.

**Comment by jonsamwell** [comment]
Thanks @BartVerm779 just doing the fix now.  Let me do this one as I'll fix #165 at the same time 👍

**Comment by jonsamwell** [comment]
Should be fixed in 3.0.0-rc.7

**Comment by AFASbart** [comment]
@jamontes79 The best you can do is open a new issue with some code and things that you tried. Also the error that you get. Jon or someone else cannot help you without any reproducible code / errors that you give us.
